spring:
  datasource:
    url: jdbc:mysql://115.79.196.67:3306/restaurant
    driverClassName: com.mysql.cj.jdbc.Driver
    username: admin
    password: Hai14031993@@@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: hainguyentran140393@gmail.com
    password: lrrihkqmaivuvwpn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 604800000 # 7 day
      refresh-token:
        expiration: 604800000 # 7 days



